# https://taskfile.dev

version: "3"

vars:
  count: 30

tasks:
  bench:
    cmds:
      - task: bench21
      - task: bench22

  bench21:
    dir: src
    cmds:
      - goup use 1.21.7
      - go version | grep '^go version go1.21.7 '
      - mkdir ../results || true
      - go test -bench=. -benchmem -count={{.count}} | testanalyzer --csv > ../results/bench_21.csv

  bench22:
    dir: src
    env:
      GOEXPERIMENT: loopvar
    cmds:
      - goup use 1.22.0
      - go version | grep '^go version go1.22.0 '
      - mkdir ../results || true
      - go test -bench=. -benchmem -count={{.count}} | testanalyzer --csv > ../results/bench_22.csv

  run21:
    dir: src
    cmds:
      - go run cmd.go

  run22:
    dir: src
    env:
      GOEXPERIMENT: loopvar
    cmds:
      - go run cmd.go
