# https://taskfile.dev

version: "3"

vars:
  count: 50

tasks:
  bench:
    cmds:
      - task: bench21
      - task: bench22

  bench21:
    dir: src
    cmds:
      - goup use 1.21.7
      - go version | grep '^go version go1.21.7 '
      - mkdir -p ../results/21 || true
      - go test -bench=. -benchmem -count={{.count}} > ../results/21/raw.txt
      - testanalyzer ../results/21/raw.txt --csv > ../results/21/summary.csv

  bench22:
    dir: src
    env:
      GOEXPERIMENT: loopvar
    cmds:
      - goup use 1.22.0
      - go version | grep '^go version go1.22.0 '
      - mkdir -p ../results/22 || true
      - go test -bench=. -benchmem -count={{.count}} > ../results/22/raw.txt
      - testanalyzer ../results/22/raw.txt --csv > ../results/22/summary.csv

  run21:
    dir: src
    cmds:
      - go run cmd.go

  run22:
    dir: src
    env:
      GOEXPERIMENT: loopvar
    cmds:
      - go run cmd.go
